---
apiVersion: v1
kind: Service
metadata:
 name: resultapp-service
 labels: 
  author: ABC
spec:
 type: LoadBalancer
 ports:
  - targetPort: 80
    port: 80
    nodePort: 32002
 selector:
  name: result-app
...
