---
apiVersion: v1
kind: Service
metadata:
 name: votingapp-service
 labels:
  author: ABC
spec:
 type: LoadBalancer
 ports:
  - targetPort: 80
    nodePort: 32001
    port: 80
 selector:
  name: voting-app
...
