---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: votingapp-deploy
 labels:
  name: voting-app
spec:
 replicas: 1
 selector:
  matchLabels:
    name: voting-app
 template:
   metadata:
    name: votingapp-pod
    labels:
     name: voting-app
   spec:
    containers:
     - name: votingapp
       image: dockersamples/examplevotingapp_vote
...
