---
apiVersion: v1
kind: Pod
metadata:
 name: nginx-pod
 labels:
  type: ABC
spec:
 containers:
  - name: nginx
    image: nginx
    volumeMounts:
     - name: my-volume
       mountPath: /usr/share/nginx/html
 volumes:
  - name: my-volume
    persistentVolumeClaim:
     claimName: mynginx-pvc
...
