---
apiVersion: v1
kind: Pod
metadata:
  name: tomee-pod
  labels:
   app: tomee
spec:
 containers:
  - name: tomee
    image: tomee
 affinity:
  nodeAffinity:
   requiredDuringSchedulingIgnoredDuringExecution:
     nodeSelectorTerms:
      - matchExpressions:
         - key: slave1
           operator: In
           values:
            - abc
...
