---
apiVersion: v1
kind: Pod
metadata:
 name: ghost-pod
 namespace: test-ns
 labels:
  type: webapplis
  author: ABC
spec:
 containers:
  - name: ghostcontainer
    image: ghost
    ports:
    - containerPort: 2368
      hostPort: 9999
    env:
    - name: NODE_ENV
      value: development
...

