---
apiVersion: v1
kind: PersistentVolume
metadata: 
 name: mysql-pv
 labels:
  author: ABC
spec:
 storageClassName: manual
 capacity:
  storage: 20Gi
 accessModes:
  - ReadWriteMany
 hostPath:
  path: /mnt/data
...

