---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: mynginx-pvc
 labels:
  type: ABC
spec:
 storageClassName: manual
 accessModes:
  - ReadWriteOnce
 resources:
  requests:
   storage: 2Gi
...
