---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: mysql-pvc
 labels:
  author: ABC
spec:
 storageClassName: manual
 accessModes:
  - ReadWriteOnce
 resources:
  requests:
   storage: 3Gi
...
