---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: mysql-pvc
 labels:
  author: ABC
spec:
 storageClassName: manual
 accessModes:
  - ReadWriteMany
 resources:
  requests:
   storage: 10Gi
...
