---
apiVersion: v1
kind: ReplicationController
metadata:
 name: tomee-rc
 labels:
  type: webserver
  author: ABC
spec:
 replicas: 2
 template:
   metadata:
    name: tomee-pod
    labels:
     name: webserver
     author: ABC
   spec:
    containers:
     - name: tomee
       image: tomee
       ports:
       - containerPort: 8080
         hostPort: 9090
...
