---
apiVersion: v1
kind: Service
metadata:
 name: my-service
 labels:
  name: headles-service
  author: ABC
spec:
 clusterIP: None
 ports:
  - targetPort: 80
    port: 80
    name: tcp
    protocol: TCP
 selector:
  name: headles-service
---
 apiVersion: apps/v1
 kind: StatefulSet
 metadata:
  name: nginx-statefulset
  labels:
   name: headles-service
 spec:
  replicas: 3
  selector:
   matchLabels:
    name: headles-service
  template:
   metadata:
    name: nginx-pod
    labels:
     name: headles-service
   spec:
    containers:
     - name: nginx
       image: nginx
       volumeMounts:
        - name: my-volume
          mountPath: /usr/share/nginx/html
    volumes:
     - name: my-volume
       persistentVolumeClaim:
        claimName: mysql-pvc
...
