---
apiVersion: v1
kind: Service
metadata:
 name: my-service
 labels:
  name: headles-service
  author: ABC
spec:
 clusterIP: None
 ports:
  - targetPort: 80
    port: 80
 selector:
  name: headles-service
---
 apiVersion: apps/v1
 kind: StatefulSet
 metadata:
  name: nginx-statefulset
  labels:
   name: headles-service
 spec:
  replicas: 3
  selector:
   matchLabels:
    name: headles-service
  template:
   metadata:
    name: nginx-pod
    labels:
     name: headles-service
   spec:
    containers:
     - name: nginx
       image: nginx
       volumeMounts:
        - name: my-volume
          mountPath: /usr/share/nginx/html/
  volumeClaimTemplates:
   - metadata:
      name: my-volume
     spec:
      accessModes: ["ReadWriteOnce"]
      resources:
       requests:
        storage: 2Gi
...
