---
apiVersion: v1
kind: Service
metadata:
 name: my-service
 labels:
  name: headles-service
spec:
 clusterIP: None
 ports:
  - targetPort: 5432
    port: 5432
    name: tcp
    protocol: TCP
 selector:
  name: headles-service
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
 name: mysql-statefulset
 labels:
  name: headles-service
spec:
 replicas: 2
 selector:
  matchLabels:
   name: headles-service
 template:
  metadata:
   name: mysql-pod
   labels:
    name: headles-service
  spec:
   containers:
    - name: mysql
      image: mysql
      volumeMounts:
        - name: my-volume
          mountPath: /var/lib/mysql
   volumes:
    - name: my-volume
      persistentVolumeClaim:
        claimName: mysql-pvc
...
