---
apiVersion: v1
kind: Pod
metadata:
 name: mysql-pod
 labels:
  type: db
spec:
 containers:
  - name: mysql
    image: mysql
    env:
     - name: MYSQL_ROOT_PASSWORD
       value: abc
 tolerations:
  - key: slave2
    operator: Equal
    value: ashok
    effect: NoSchedule
  - key: slave1
    operator: Equal
    value: abc
    effect: NoSchedule
...
