---
apiVersion: v1
kind: Pod
metadata:
 name: tomcat-pod
 labels:
  type: web
spec:
 containers:
  - name: tomcat
    image: tomcat
 tolerations:
   - key: slave1
     operator: Equal
     value: abc
     effect: NoSchedule
...
