---
apiVersion: v1
kind: Pod
metadata:
 name: redis-pod
 labels:
  author: ABC
spec:
 containers:
  - name: redis-container
    image: redis
    volumeMounts:
     - name: redis-volume
       mountPath: /data/redis
 volumes:
  - name: redis-volume
    emptyDir: {}
...
    
