---
apiVersion: v1
kind: Pod
metadata:
 name: mysql-pod
 labels:
  type: db
spec:
 containers:
  - name: mysql-pod
    image: mysql
    env:
     - name: MYSQL_ROOT_PASSWORD
       value: ABC
    volumeMounts:
     - name: mysql-volume
       mountPath: /var/lib/mysql
 volumes:
  - name: mysql-volume
    emptyDir: {}
...
     
