---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: redis-deploy
 labels:
  name: redis-app
  author: ABC
spec:
 replicas: 1
 selector:
  matchLabels:
   name: redis-app
 template:
   metadata:
     name: redis-pod
     labels:
      name: redis-app
   spec:
    containers:
      - name: redis-app
        image: redis
...

