---
apiVersion: v1
kind: Service
metadata:
  name: resultapp-service
  labels:
   name: resultapp-service
   author: ABC
spec:
 type: LoadBalancer
 ports:
  - targetPort: 80
    nodePort: 32007
    port: 80
 selector:
  name: result-app
...
