---
apiVersion: v1
kind: Pod
metadata:
 name: tomee-pod
 labels:
  type: webapp
spec:
 containers:
  - name: tomee
    image: tomee
    ports:
     - containerPort: 8080
       hostPort: 8888
    resources:
      requests:
       memory: "70Mi"
       cpu: "200m"
      limits:
       memory: "150Mi"
       cpu: "500m"
...
