---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: ghost-deployment
 labels:
   type: webapp
   author: ABC
spec:
 replicas: 2
 selector:
   matchLabels:
    type: webapp
 template:
  metadata:
    name: ghost-pod
    labels:
     type: webapp
     author: ABC
  spec:
   containers:
     - name: ghost
       image: ghost
       env:
        - name: NODE_ENV
          value: development
       ports:
        - containerPort: 2368
          hostPort: 9090
...

