---
apiVersion: v1
kind: Pod
metadata:
 name: nginx-pod
 labels:
   type: webserver
   author: ABC
spec:
 containers:
  - name: mynginx
    image: nginx
    ports:
      - containerPort: 8080
        hostPort: 9090

...

