---
apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod1
  labels:
    type: db
    author: abc
spec:
  containers:
    - name: mydb
      image: postgres
      env:
        - name: POSTGRES_PASSWORD
          value: abc
        - name: POSTGRES_USER
          value: abcuser
        - name: POSTGRES_DB
          value: abcdb
...
