---
apiVersion: v1
kind: Pod
metadata:
 name: tomcat-pod
 labels:
  type: webserver
  author: abc

spec:
 containers:
   - name: tomcat
     image: tomee
     ports:
      - containerPort: 8080
        hostPort: 8888
...
