---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
 name: jenkins-rs
 labels:
   type: cicd-rs
   author: ABC
spec:
 replicas: 2
 selector:
  matchLabels:
   type: cicd-rs
 template:
  metadata:
     name: jenkins-pod
     labels:
       type: cicd-rs
       author: ABC
  spec:
    containers:
       - name: jenkins
         image: jenkins/jenkins
         ports:
           - containerPort: 8080
             hostPort: 9090
...
      
  
