---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
 name: nginx-rs
 labels:
  type: webserver
  author: ABC
spec:
 replicas: 2
 selector:
  matchLabels:
   type: webserver
 template:
  metadata:
    name: nginx-pod
    labels:
     type: webserver
     author: ABC
  spec:
   containers:
    - name: nginx
      image: nginx
      ports:
       - containerPort: 80
         hostPort: 9090
...
