---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
 name: tomcat-rs
 labels:
  type: webserver
  author: ABC
spec:
 replicas: 2
 selector:
  matchLabels:
    type: webserver
 template:
  metadata:
    name: tomcat-pod
    labels:
     type: webserver
     author: ABC
  spec:
    containers:
     - name: tomee
       image: tomee
       ports:
       - containerPort: 8080
         hostPort: 9090
...
