---
apiVersion: v1
kind: Service
metadata:
 name: lb-service
 labels:
  author: ABC
spec:
 type: LoadBalancer
 ports:
  - targetPort: 2368
    nodePort: 32700
    port: 2368
 selector:
  type: webapp
... 
