---
apiVersion: v1
kind: Service
metadata:
 name: tomee-service
 labels:
  author: ABC
spec:
 type: NodePort
 selector:
  type: webversion
 ports:
 - targetPort: 8080
   nodePort: 32002
   port: 9090
...
